version: "3.9"

services:
  db:
    image: postgres:15
    container_name: raju
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
